--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 21-01-2026 15:46:07
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO trading_db.categories(id, name) VALUES
(4, 'Breakout');
INSERT INTO trading_db.categories(id, name) VALUES
(1, 'Price Action');
INSERT INTO trading_db.categories(id, name) VALUES
(5, 'Reversal');
INSERT INTO trading_db.categories(id, name) VALUES
(3, 'Support/Resistance');
INSERT INTO trading_db.categories(id, name) VALUES
(2, 'Volume');