--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 21-01-2026 15:46:07
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO trading_db.checklist_rules(id, rule_text, is_checked) VALUES
(1, 'Trend is aligned with trade?', 0);
INSERT INTO trading_db.checklist_rules(id, rule_text, is_checked) VALUES
(2, 'Stop Loss defined and accepted?', 0);
INSERT INTO trading_db.checklist_rules(id, rule_text, is_checked) VALUES
(3, 'Risk/Reward is at least 1:2?', 0);
INSERT INTO trading_db.checklist_rules(id, rule_text, is_checked) VALUES
(4, 'No major news event upcoming?', 0);
INSERT INTO trading_db.checklist_rules(id, rule_text, is_checked) VALUES
(5, 'Not tilting / revenge trading?', 0);